title: Taehun's Blog
description: Taehun's Technical Blog
author: 김태훈 (Taehun "Brian" Kim)
avatar: https://avatars.githubusercontent.com/u/374109?s=400&u=f9bedee4ca83dceee7ee57caf598a819284d2637&v=4
bio: 임베디드 개발자 출신 머신러닝 엔지니어 입니다. MLOps와 딥러닝 모델 최적화 관련 업무와 공부를 하고 있습니다.
email: kth3321@gmail.com
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
disqus: taehuns-blog

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: https://avatars.githubusercontent.com/u/374109?s=400&u=f9bedee4ca83dceee7ee57caf598a819284d2637&v=4
social:
  name: Taehun Kim
  links:
    - https://www.linkedin.com/in/taehun-brian-kim/
    - https://github.com/Taehun
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko

# Google Analytics
google_analytics: G-9TM0JNV0ZK

excerpt_separator: <!--more-->
